volumes:
    wildfly_persistence: {}

services:
    application:
        container_name: lab2-web
        build:
            context: .
            dockerfile: Dockerfile-dev
        environment:
            - WILDFLY_USERNAME=admindev
            - WILDFLY_PASSWORD=admindev
            - WILDFLY_PUBLIC_LISTEN_ADDRESS=0.0.0.0
            - WILDFLY_MANAGEMENT_LISTEN_ADDRESS=0.0.0.0
        volumes:
            - wildfly_persistence:/bitnami/wildfly
        ports:
            - "8080:8080"
            - "9990:9990"